### ISSUE TITLE
Empty XML in MuseScore 4

### ISSUE THREAD

**Issue by Aeliffa** [jeetee/abc_import#5]
I've tried converting several different ABC files and so far none have worked. It loads the song title and a single empty measure and that's it. I ran it through a notepad++ filter checking for non-ascii character and didn't find anything amiss in any of them.

I'll attach some of the abc files I used as well as the xml files that were generated.

[Aeliffa's ABC Issues.zip](https://github.com/jeetee/abc_import/files/11927047/Aeliffa.s.ABC.Issues.zip)

**Comment by jeetee** [comment]
My server runs version 237 of Wim Vree's abc2xml python script. I've noticed 239 is out now, but it produces exactly the same output. I see no errors logged in the server logs, so I suggest taking this issue up to him for better investigation and to determine whether his convertor has a bug/missing feature or whether the program you've used to create those files is not following the ABC-standard.

His contact details can be found at the bottom of https://wim.vree.org/svgParse/abc2xml.html , feel free to point him to the issue here as well if he wishes to discuss in more depth.
